### ISSUE TITLE
Bug: slice out of bound for vsco.co website

### ISSUE THREAD

**Issue by jammutkarsh** [alenjohn05/ryze#1]
I used this tool twice for different emails, both panicked on [vsco code](https://github.com/alenjohn05/ryze/blob/main/cmd/apps/vsco.go) and is concerned with [L39](https://github.com/alenjohn05/ryze/blob/main/cmd/apps/vsco.go#L39).

```bash
$ ryze personalmail@gmail.com
Where are you personalmail@gmail.com ? 🧐
Spotify 👀
Twitter 👀
Adobe 👀
Instagram 👀
panic: runtime error: slice bounds out of range [:-1]

goroutine 10 [running]:
github.com/alenjohn05/ryze/cmd/apps.getVSID()
	/Users/utc/go/pkg/mod/github.com/alenjohn05/ryze@v0.0.0-20231023154310-11217f5c5d22/cmd/apps/vsco.go:39 +0x2b2
github.com/alenjohn05/ryze/cmd/apps.Vsco(0x0?, {0x7ff7bfeff7d5, 0x1d}, 0x0)
	/Users/utc/go/pkg/mod/github.com/alenjohn05/ryze@v0.0.0-20231023154310-11217f5c5d22/cmd/apps/vsco.go:46 +0x7d
created by github.com/alenjohn05/ryze/cmd.glob..func1 in goroutine 1
	/Users/utc/go/pkg/mod/github.com/alenjohn05/ryze@v0.0.0-20231023154310-11217f5c5d22/cmd/root.go:37 +0x4c9
# ------------------------------------------------------------------------------------------	
$ ryze mail@mydomain.in
Where are you mail@mydomain.in ? 🧐
panic: runtime error: slice bounds out of range [:-1]

goroutine 23 [running]:
github.com/alenjohn05/ryze/cmd/apps.getVSID()
	/Users/utc/go/pkg/mod/github.com/alenjohn05/ryze@v0.0.0-20231023154310-11217f5c5d22/cmd/apps/vsco.go:39 +0x2b2
github.com/alenjohn05/ryze/cmd/apps.Vsco(0x0?, {0x7ff7bfeff7d5, 0x18}, 0x0)
	/Users/utc/go/pkg/mod/github.com/alenjohn05/ryze@v0.0.0-20231023154310-11217f5c5d22/cmd/apps/vsco.go:46 +0x7d
created by github.com/alenjohn05/ryze/cmd.glob..func1 in goroutine 1
	/Users/utc/go/pkg/mod/github.com/alenjohn05/ryze@v0.0.0-20231023154310-11217f5c5d22/cmd/root.go:37 +0x4c9
```

From what I know, what you are searching for is out of bound.

**Comment by jammutkarsh** [comment]
Btw, it's a nice project I would love see more apps!
